from typing import Protocol
from nautilus_trader.model import Bar
from nautilus_trader.model.instruments import Instrument
from order.order_validator import TradingRulesMutable


class Provider(Protocol):
    pass


class ActorInfoProvider(Provider):
    def get_snapshot_intraday_high(self, instrument_id: str) -> float: ...
    def get_intraday_atr(self, instrument_id: str) -> float: ...
    def get_snapshot_intraday_low(self, instrument_id: str) -> float: ...
    def get_latest_bar_with_trading_bar_type(self, instrument_id: str) -> Bar: ...
    def get_intraday_realized_pnl(self) -> float: ...
    def get_trading_rule(self) -> TradingRulesMutable: ...
    def get_instrument(self, instrument_id: str) -> Instrument: ...


PROVIDER_REGISTRY = {"actor_info_provider": ActorInfoProvider}
