import datetime
from typing import Protocol, TypeVar
from nautilus_trader.model import Bar
from nautilus_trader.model.enums import OrderSide, PositionSide
from nautilus_trader.model.position import Position
from nautilus_trader.model.orders import Order
from nautilus_trader.model import InstrumentId
from nautilus_trader.model.instruments import Instrument

from schemas import TradingRulesMutable


class Provider(Protocol):
    pass


PG = TypeVar("PG", bound=Provider)


class ActorInfoProvider(Provider):
    def get_snapshot_intraday_high(self, instrument_id: InstrumentId) -> float: ...
    def get_intraday_atr(self, instrument_id: InstrumentId) -> float: ...
    def get_snapshot_intraday_low(self, instrument_id: InstrumentId) -> float: ...
    def get_latest_bar_with_trading_bar_type(
        self, instrument_id: InstrumentId
    ) -> Bar: ...
    def get_intraday_realized_pnl(self) -> float: ...
    def get_trading_rule(self) -> TradingRulesMutable: ...
    def get_instrument(self, instrument_id: InstrumentId) -> Instrument: ...
    def get_current_datetime(self) -> datetime.datetime: ...
    def get_positions(self) -> dict: ...
    def get_open_positions(
        self, side: PositionSide, instrument_id: InstrumentId
    ) -> list[Position]: ...
    def get_open_orders(
        self, side: OrderSide, instrument_id: InstrumentId
    ) -> list[Order]: ...
    def get_unrealized_profit_and_loss(self) -> float: ...
    def get_realized_profit_and_loss(self) -> float: ...
    def get_depolyed_balance(self, instrument_id: InstrumentId) -> float: ...


PROVIDER_REGISTRY = {"actor_info_provider": ActorInfoProvider}
